version: '3.8'

services:
  magasin-app:
    build:
      context: .
      dockerfile: magasincentral/Dockerfile
    container_name: log430-lab2-magasin-app
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION=Host=magasin-db;Port=5432;Username=postgres;Password=postgres;Database=magasin
    depends_on:
      - magasin-db

  magasin-db:
    image: postgres:16
    container_name: log430-lab2-magasin-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: magasin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
