version: '3.8'

services:
  web:
    build: .
    container_name: log430-lab2-client
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION=Host=db;Port=5432;Username=postgres;Password=postgres;Database=magasin
    depends_on:
      - db

  db:
    image: postgres
    container_name: log430-lab2-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: magasin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
